# Generated by Django 4.2.2 on 2023-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas_campeonato',
            name='logo',
            field=models.ImageField(upload_to='caracteristicas/tournament_logos/'),
        ),
    ]
