# Generated by Django 4.2.2 on 2023-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0002_alter_caracteristicas_campeonato_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas_campeonato',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='caracteristicas/tournament_logos/'),
        ),
    ]
