# Generated by Django 4.2.2 on 2023-07-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0002_alter_mesa_pareja_dos_alter_mesa_pareja_uno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.IntegerField()),
                ('puntos_pareja_uno', models.IntegerField()),
                ('puntos_pareja_dos', models.IntegerField()),
                ('res_par_uno', models.IntegerField()),
                ('res_par_dos', models.IntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesas.mesa')),
            ],
        ),
    ]
