# Generated by Django 4.2.2 on 2023-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_alter_resultado_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='n_pareja_dos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='n_pareja_uno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='nombre_pareja_dos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='nombre_pareja_uno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
