# Generated by Django 4.2.2 on 2023-09-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0005_mesa_resultado'),
        ('resultados', '0003_resultado_n_pareja_dos_resultado_n_pareja_uno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='mesas.mesa'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntos_pareja_dos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntos_pareja_uno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('mesa', 'partida')},
        ),
    ]
