# Generated by Django 4.2.2 on 2023-09-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0006_alter_mesa_resultado'),
        ('resultados', '0004_alter_resultado_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='mesa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado_mesa', to='mesas.mesa'),
        ),
    ]
