"""recreate tables with proper relationships

Revision ID: 63a676248d8b
Revises: 
Create Date: 2024-11-13 11:35:30.269350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a676248d8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campeonatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('dias_duracion', sa.Integer(), nullable=True),
    sa.Column('numero_partidas', sa.Integer(), nullable=True),
    sa.Column('grupo_b', sa.Boolean(), nullable=True),
    sa.Column('partida_actual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campeonatos_id'), 'campeonatos', ['id'], unique=False)
    op.create_index(op.f('ix_campeonatos_nombre'), 'campeonatos', ['nombre'], unique=False)
    op.create_table('parejas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('campeonato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campeonato_id'], ['campeonatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parejas_id'), 'parejas', ['id'], unique=False)
    op.create_index(op.f('ix_parejas_nombre'), 'parejas', ['nombre'], unique=False)
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('pareja_id', sa.Integer(), nullable=True),
    sa.Column('campeonato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campeonato_id'], ['campeonatos.id'], ),
    sa.ForeignKeyConstraint(['pareja_id'], ['parejas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'apellido', 'campeonato_id', name='uq_jugador_campeonato')
    )
    op.create_index(op.f('ix_jugadores_apellido'), 'jugadores', ['apellido'], unique=False)
    op.create_index(op.f('ix_jugadores_id'), 'jugadores', ['id'], unique=False)
    op.create_index(op.f('ix_jugadores_nombre'), 'jugadores', ['nombre'], unique=False)
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('campeonato_id', sa.Integer(), nullable=True),
    sa.Column('partida', sa.Integer(), nullable=False),
    sa.Column('pareja1_id', sa.Integer(), nullable=True),
    sa.Column('pareja2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campeonato_id'], ['campeonatos.id'], ),
    sa.ForeignKeyConstraint(['pareja1_id'], ['parejas.id'], ),
    sa.ForeignKeyConstraint(['pareja2_id'], ['parejas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_id'), 'mesas', ['id'], unique=False)
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campeonato_id', sa.Integer(), nullable=True),
    sa.Column('P', sa.Integer(), nullable=True),
    sa.Column('M', sa.Integer(), nullable=True),
    sa.Column('id_pareja', sa.Integer(), nullable=True),
    sa.Column('GB', sa.String(), nullable=True),
    sa.Column('PG', sa.Integer(), nullable=True),
    sa.Column('PP', sa.Integer(), nullable=True),
    sa.Column('RP', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['M'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['campeonato_id'], ['campeonatos.id'], ),
    sa.ForeignKeyConstraint(['id_pareja'], ['parejas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_id'), 'resultados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_id'), table_name='resultados')
    op.drop_table('resultados')
    op.drop_index(op.f('ix_mesas_id'), table_name='mesas')
    op.drop_table('mesas')
    op.drop_index(op.f('ix_jugadores_nombre'), table_name='jugadores')
    op.drop_index(op.f('ix_jugadores_id'), table_name='jugadores')
    op.drop_index(op.f('ix_jugadores_apellido'), table_name='jugadores')
    op.drop_table('jugadores')
    op.drop_index(op.f('ix_parejas_nombre'), table_name='parejas')
    op.drop_index(op.f('ix_parejas_id'), table_name='parejas')
    op.drop_table('parejas')
    op.drop_index(op.f('ix_campeonatos_nombre'), table_name='campeonatos')
    op.drop_index(op.f('ix_campeonatos_id'), table_name='campeonatos')
    op.drop_table('campeonatos')
    # ### end Alembic commands ###
