# Generated by Django 4.2.2 on 2023-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parejas',
            name='Club_pertenencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
