# Generated by Django 4.2.2 on 2023-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_alter_parejas_club_pertenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='parejas',
            name='SerieB',
            field=models.BooleanField(default=False),
        ),
    ]
