# Generated by Django 4.2.2 on 2023-09-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_parejas_serieb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parejas',
            name='Numero_pareja',
        ),
    ]
