# Generated by Django 4.2.2 on 2023-07-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='pareja_dos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='pareja_uno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
