# Generated by Django 4.2.2 on 2023-08-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesa_pareja_dos_alter_mesa_pareja_uno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='id',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de Mesa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='pareja_dos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de la segunda pareja'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='pareja_uno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de la primera pareja'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='partida',
            field=models.IntegerField(default=1, verbose_name='Número de Partida'),
        ),
    ]
