# Generated by Django 4.2.2 on 2023-08-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_alter_mesa_options_remove_mesa_id_alter_mesa_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='nombre_pareja_dos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la segunda pareja'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='nombre_pareja_uno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la primera pareja'),
        ),
    ]
