# Generated by Django 4.2.2 on 2023-09-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_resultado_n_pareja_dos_resultado_n_pareja_uno_and_more'),
        ('mesas', '0004_mesa_nombre_pareja_dos_mesa_nombre_pareja_uno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='resultado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado_mesa', to='resultados.resultado'),
        ),
    ]
