# Generated by Django 4.2.2 on 2023-09-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0004_alter_resultado_mesa_and_more'),
        ('mesas', '0005_mesa_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa_resultado', to='resultados.resultado'),
        ),
    ]
