# Generated by Django 4.2.2 on 2023-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0006_alter_mesa_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='resultado',
        ),
        migrations.AddField(
            model_name='mesa',
            name='resultado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
