# Generated by Django 4.2.2 on 2023-07-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('serieB', models.BooleanField(default=False)),
                ('partidas_ganadas', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('partida', models.IntegerField(default=0)),
                ('pareja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.parejas')),
            ],
        ),
    ]
